### ISSUE TITLE
Jenkins fails to start exhausting number of open files 

### ISSUE THREAD

**Issue by vjuranek** [jenkinsci/openstack-cloud-plugin#175] opened 2017-09-25 19:53 UTC
After upgrading to OS plugin `2.25` (from `2.22`), Jenkins failed to start as `resource-disposer-plugin` failed to create new tmp files (`atomic*.tmp`), exceeding limits on open files. Reverting back to `2.22` solved the issue. 

Sorry for very brief report, this is rather warning there's some problem. It happened on production system and I have to reverted all changes ASAP without any deeper investigation.

**Comment by vjuranek** [comment] 2017-09-25 20:05
probably could be related: I just found out that in our OS tenant is one VM instance which cannot be deleted (OS fails to delete this instance)

**Comment by olivergondza** [comment] 2017-09-26 08:07
That sounds it might be caused by https://github.com/jenkinsci/openstack-cloud-plugin/issues/168 that require o-c-p 2.25 and r-d-p 0.8 (I presume you are using older version here). Though the way it manifested was a bit surprising as well as the fact you do not observe it with 2.22. I have deployed the same version yesterday and have not observed similar problems so far.

---

Note that version 2.25 changed the persistence format of *Slave Type*/*Launcher Factory* so generally downgrade can loose the date (slave type and `credentialsId`).

**Comment by olivergondza** [comment] 2017-09-26 11:15
Now I have it confirmed the problem was either caused or at least amplified by resource-disposer. Shortly after Jenkins restart, it scheduled all tracked disposer items to be discarded and, at least according to the log, 80+ has hit the file number limit within *one second* when trying to persist the collections after they completed. Chances are, there ware lot more of them scheduled. As already reported, this is addressed by resource-disposer v0.8 as individual items does not persists the whole collection when they complete. This scaled quite poorly because as the collection grew, the concurrent writes are more frequent and there is more data to write...

**Closed** 2017-09-26 11:18 UTC
