### ISSUE TITLE
The configureClouds page has invalid rendering

### ISSUE THREAD

**Issue by kofemann** [jenkinsci/openstack-cloud-plugin#313] opened 2021-03-18 10:11 UTC
### Version report

Jenkins: 2.2.84
OpenStack Cloud Plugin: 2.56

Browser console reports:
```
hudson-behavior.js:49 TypeError: e.getAttribute is not a function
    at findFormParent (hudson-behavior.js:2538)
    at findNearBy (hudson-behavior.js:260)
    at hudson-behavior.js:1500
    at hudson-behavior.js:47
    at prototype.js:853
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:852)
    at refillOnChange (hudson-behavior.js:1499)
    at select.js:104
    at Array.forEach (<anonymous>)
```
![Screenshot from 2021-03-18 10-59-45](https://user-images.githubusercontent.com/575965/111609408-8b065380-87da-11eb-9482-7c436150c905.png)

When I click on `Add a new Cloud` then nothing happens.

**Comment by olivergondza** [comment] 2021-03-19 21:25
This feels like already reported breakage caused by core change: https://issues.jenkins.io/browse/JENKINS-65157

**Comment by ondrejbudai** [comment] 2021-03-21 14:26
I have the same issue, is there a plan to fix it?

**Comment by olivergondza** [comment] 2021-03-24 11:40
This have to fixed ASAP, no question about that. I will look at it as soon as time permits.

I am closing this Issue. Please use the JIRA instead.

**Closed by olivergondza** 2021-03-24 11:40 UTC
Labels: bug

**Comment by ondrejbudai** [comment] 2021-04-19 07:15
I see that #314 got merged, thanks a lot! Can we get a release so I don't have to use a manually built plugin? Thanks again! :)
