### ISSUE TITLE
env.OPENSTACK_PUBLIC_IP contains the real IP and not the floating IP

### ISSUE THREAD

**Issue by Bloeffy** [jenkinsci/openstack-cloud-plugin#295] opened 2020-03-27 11:41 UTC
Since the update to 2.52 we got the problem that env.OPENSTACK_PUBLIC_IP in the Jenkinsfile contains the real IP and not the floating IP. The floating IP got created, but not set into the variable.

My guess is that it is due to the export as an env-var.

The following log is a section of the relevant part

```
2020-03-26 03:59:49.846+0000 [id=31584] INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-186 with options jenkins.plugins.openstack.compute.SlaveOptions@6388c7b1[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false]
}, NovaAddress{address=192.168.10.113, type=floating, version=4, macaddr=fa:16:3e:1e:11:c8, 
2020-03-26 07:21:39.550+0000 [id=37111] INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-192 with options jenkins.plugins.openstack.compute.SlaveOptions@20a4b508[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false]
}, NovaAddress{address=192.168.10.120, type=floating, version=4, macaddr=fa:16:3e:6c:3d:85, 
}, NovaAddress{address=192.168.10.120, type=floating, version=4, macaddr=fa:16:3e:6c:3d:85, 
2020-03-26 07:31:59.564+0000 [id=36612] INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-193 with options jenkins.plugins.openstack.compute.SlaveOptions@4a5c2f99[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false] 
}, NovaAddress{address=192.168.10.122, type=floating, version=4, macaddr=fa:16:3e:4b:5b:81, 
2020-03-26 08:33:03.828+0000 [id=62]    INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-199 with options jenkins.plugins.openstack.compute.SlaveOptions@1ba89533[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false] 
}, NovaAddress{address=192.168.10.123, type=floating, version=4, macaddr=fa:16:3e:1f:e7:51, 
2020-03-27 03:51:20.170+0000 [id=68073] INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-341 with options jenkins.plugins.openstack.compute.SlaveOptions@30f8a6b7[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false] 
}, NovaAddress{address=192.168.10.131, type=floating, version=4, macaddr=fa:16:3e:2c:46:7c,  
2020-03-27 08:24:07.201+0000 [id=350]   INFO    j.p.o.c.JCloudsSlaveTemplate#provisionServer: Provisioning new openstack server ubuntu1804-64-cloud-doctest-0 with options jenkins.plugins.openstack.compute.SlaveOptions@6811e829[bootSource=Image Ubuntu bionic server amd64 2020-03-01,hardwareId=3,networkId=f3bc6398-4373-4cc3-adf6-b33f4bb4fea3,userDataId=4290de88-ecbd-46f1-b876-0a6a42aa1ac5,instanceCap=20,instancesMin=0,floatingIpPool=ext-net,securityGroups=default,availabilityZone=nova,startTimeout=600000,keyPairName=<null>,numExecutors=1,jvmOptions=<null>,fsRoot=jenkins,launcherFactory=jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$JNLP@1f,nodeProperties=<null>,retentionTime=30,configDrive=false] 
}, NovaAddress{address=192.168.10.133, type=floating, version=4, macaddr=fa:16:3e:b4:be:38,
```

**Comment by olivergondza** [comment] 2020-03-27 13:27
Thanks for the report. That particular release, does not seem to change any relevant code: https://github.com/jenkinsci/openstack-cloud-plugin/releases/tag/openstack-cloud-2.52. What is the previous release where this used to work for you?

Also, can you confirm the nodes `OPENSTACK_PUBLIC_IP` contains the server's fixed IP instead of the floating one?

**Comment by Bloeffy** [comment] 2020-03-27 14:29
Thanks for the fast answer. Yes, i can confirm that the ```OPENSTACK_PUBLIC_IP``` contains the server´s fixed IP instead of the floating one. In the 2.51 release it contained the floating IP

**Comment by olivergondza** [comment] 2020-03-27 16:17
The difference between the releases icontians the move from Compute Networking API to Neutron API[1]. I would find it more likely the server fails to allocate FIP and then falls back to using the fixed one, but the "access IP" identification is unchanged. Here are some more ideas:

- Does the problem appear consistently (with every node using FIPs)?
- Is the floating IP correctly assigned?
- Can you attach full logs related to certain affected node?
- What IP address is used to connect to that node (provided SSH launcher is used)? You can find this in the slave log.

[1] https://github.com/jenkinsci/openstack-cloud-plugin/compare/openstack-cloud-2.51...openstack-cloud-2.52#diff-4f0d738875d807e35d62ee8a3fe3c1b6

**Comment by mgonzal1** [comment] 2020-03-31 20:24
I got the same issue with version 2.52
The Floating IP is correctly assigned but tries to use fixed IP to connect using SSH launcher

**Comment by rfateam2** [comment] 2020-04-01 02:06
The issue is reproducing with Jenkins 2.222.1 and plugin version 2.52. Jenkins is trying to establish SSH connection randomly to real IP instead FIP. Workaround is to creating network with external IP subnet. 
Worked fine before with previous versions of Jenkins 2.204.2 and plugin version 2.51

**Comment by donnydavis** [comment] 2020-04-01 10:17
I had to downgrade back to 2.51 to get this plugin working again.

**Comment by Bloeffy** [comment] 2020-04-01 12:52
@olivergondza The other comments answered some of your questions in my opinion. Do you need any more information?

**Comment by olivergondza** [comment] 2020-04-01 17:59
@Bloeffy, somewhat, thanks. Though I still do not see how this could be happening.

Please run this [diagnosing script in groovy console](https://plugins.jenkins.io/openstack-cloud/#user-content-access-openstack-client-from-groovy-console) and report what is says for _affected servers_:

```groovy
import jenkins.plugins.openstack.compute.internal.Openstack

jenkins.plugins.openstack.compute.JCloudsCloud.clouds.each {
  println it.name
  it.openstack.runningNodes.each {
    println "${accip(it)}: ${it.addresses.toString().replaceAll('\n', '')}"
  }
}

def accip(server) {
  try {
    return Openstack.getAccessIpAddress(server)
  } catch (java.util.NoSuchElementException ex) {
    return ex
  }
}

return
```

It has the format of ACCESS_IP: ALL_IPS. This should test the hypothesis the plugin is failing to identify the most suitable IP.

**Comment by rfateam2** [comment] 2020-04-04 18:45
@olivergondza 
`# Has been connected successfully 
192.171.17.109: NovaAddresses{addresses={jenkins_slave=[NovaAddress{address=192.168.1.11, type=fixed, version=4, macaddr=fa:16:3e:60:5b:6f, }, NovaAddress{address=192.171.17.109, type=floating, version=4, macaddr=fa:16:3e:60:5b:6f, }]}, }

# Failed to connect to jenkins in couple minutes on the same openstack with the same slave label
192.171.17.117: NovaAddresses{addresses={jenkins_slave=[NovaAddress{address=192.168.1.20, type=fixed, version=4, macaddr=fa:16:3e:e2:00:89, }, NovaAddress{address=192.171.17.117, type=floating, version=4, macaddr=fa:16:3e:e2:00:89, }]}, }`

`Addresses | 192.168.1.20 (fixed in jenkins_slave), 192.171.17.117 (floating in jenkins_slave)`

Log from Jenkins node
`SSHLauncher{host='192.168.1.20', port=22, credentialsId='....59d7-4e39-8b28....', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=600, maxNumRetries=5, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[04/04/20 09:36:07] [SSH] Opening SSH connection to 192.168.1.20:22.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 5 more retries left.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 4 more retries left.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 3 more retries left.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 2 more retries left.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 1 more retries left.
Connection timed out (Connection timed out)
ERROR: Connection is not established!
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:988)`

**Comment by olivergondza** [comment] 2020-04-04 19:14
@rfateam2, thanks! This tells us the plugin is capable of extracting the suitable IP of running server, but - for some reason - different one was used by the launcher. What is happening can be explained but the floating ip not to be there yet, but that is a theory for now.

Can you check what does the server log contains for the affected server? It is expected to print "Amended server: " that contains both the fixed and floating IP address. If it contains only the fixed ones, we know we have nailed it...

**Comment by andrewdmcleod** [comment] 2020-04-07 12:02
Also affected, v2.52- private IP is allocated, reported server details:

Addresses | 10.5.0.3 (fixed in admin_net), 10.245.163.189 (floating in admin_net)
-- | --

OPENSTACK_PUBLIC_IP=10.5.0.3

Tried twice, same problem.
fwiw, I am using the metadata service during cloud-init to get the allocated public IP and this is working.

Downgraded to 2.51, retested, works OK

**Comment by olivergondza** [comment] 2020-04-07 12:43
@andrewdmcleod, thanks. What would help to move this forward is the relevant part of the server log (see above).

**Comment by rfateam2** [comment] 2020-04-07 17:06
@olivergondza logs are below.
`// Jenkins
OpenStack details
Server Id	3b46ab81-6255-4509-b89a-ebec5c399014
Addresses	192.168.1.23 (fixed in jenkins_slave), 192.171.17.115 (floating in jenkins_slave)
metadata.jenkins-boot-image-id	92bf9d42-a5ac-45f5-aa61-437d61661229
metadata.jenkins-boot-source	Image jenkins-slave-master
Network(s)	jenkins_slave
Floating Ip Pool	ext_network
Security Groups	jenkins
Start Timeout (ms)	600000
Launcher Factory	SSH


//Node's logs

SSHLauncher{host='192.168.1.23', port=22, credentialsId='0846289d-59d7-4e39-8b28-7ef3e24ae269', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=600, maxNumRetries=5, retryWaitTime=15, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[04/07/20 09:54:17] [SSH] Opening SSH connection to 192.168.1.23:22.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)", retrying in 15 seconds. There are 5 more retries left.

// Server's logs

Apr 07, 2020 9:53:42 AM jenkins.plugins.openstack.compute.internal.Openstack debug
FINE: Machine started: ops-vm-rtp-jnlp-1011
Apr 07, 2020 9:53:42 AM jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
FINE: Assigning floating IP from ext_network to ops-vm-rtp-jnlp-1011
Apr 07, 2020 9:53:42 AM jenkins.plugins.openstack.compute.internal.Openstack debug
FINE: Allocating floating IP for ops-vm-rtp-jnlp-1011 in ops-vm-rtp-jnlp-1011
Apr 07, 2020 9:53:48 AM jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
INFO: Amended server: NovaServer{id=3b46ab81-6255-4509-b89a-ebec5c399014, name=ops-vm-rtp-jnlp-1011, image={id=92bf9d42-a5ac-45f5-aa61-437d61661229, links=[{href=http://10.0.0.100:8774/b909f16ff0d24689a7ad9891268474da/images/92bf9d42-a5ac-45f5-aa61-437d61661229, rel=bookmark}]}, flavor=NovaFlavor{id=5c3f27ed-2b9b-4f7f-8766-1142e69e6454, ephemeral=0, swap=0, rxtx_factor=1.0, links=[GenericLink{href=http://10.0.0.100:8774/b909f16ff0d24689a7ad9891268474da/flavors/5c3f27ed-2b9b-4f7f-8766-1142e69e6454, rel=bookmark}],
}, status=ACTIVE, diskconfig=MANUAL, userId=a9f65e9517ba4fa2a2f2963b76832b48, created=Tue Apr 07 09:53:31 PDT 2020, updated=Tue Apr 07 09:53:41 PDT 2020, launched at=Tue Apr 07 09:53:41 PDT 2020, tenantId=b909f16ff0d24689a7ad9891268474da, hostId=9ea2f3bced5ac7974c05232b142aff5ffd1dab4af6a531ac92a45226, addresses=NovaAddresses{addresses={jenkins_slave=[NovaAddress{address=192.168.1.23, type=fixed, version=4, macaddr=fa:16:3e:07:00:fe,
}]},
}, powerstate=1, vmState=active, metadata={jenkins-boot-image-id=92bf9d42-a5ac-45f5-aa61-437d61661229, jenkins-cloud-name=openstack-rtp, jenkins-template-name=ops-vm-rtp-jnlp, jenkins-instance=https://jenkins.infra.server.com/, jenkins-scope=node:ops-vm-rtp-jnlp-1011:1392152704, jenkins-boot-source=Image jenkins-slave-master}}
Apr 07, 2020 9:53:48 AM jenkins.plugins.openstack.compute.JCloudsSlaveTemplate provisionServer
INFO: Provisioned: NovaServer{id=3b46ab81-6255-4509-b89a-ebec5c399014, name=ops-vm-rtp-jnlp-1011, image={id=92bf9d42-a5ac-45f5-aa61-437d61661229, links=[{href=http://10.0.0.100:8774/b909f16ff0d24689a7ad9891268474da/images/92bf9d42-a5ac-45f5-aa61-437d61661229, rel=bookmark}]}, flavor=NovaFlavor{id=5c3f27ed-2b9b-4f7f-8766-1142e69e6454, ephemeral=0, swap=0, rxtx_factor=1.0, links=[GenericLink{href=http://10.0.0.100:8774/b909f16ff0d24689a7ad9891268474da/flavors/5c3f27ed-2b9b-4f7f-8766-1142e69e6454, rel=bookmark}],
}, status=ACTIVE, diskconfig=MANUAL, userId=a9f65e9517ba4fa2a2f2963b76832b48, created=Tue Apr 07 09:53:31 PDT 2020, updated=Tue Apr 07 09:53:41 PDT 2020, launched at=Tue Apr 07 09:53:41 PDT 2020, tenantId=b909f16ff0d24689a7ad9891268474da, hostId=9ea2f3bced5ac7974c05232b142aff5ffd1dab4af6a531ac92a45226, addresses=NovaAddresses{addresses={jenkins_slave=[NovaAddress{address=192.168.1.23, type=fixed, version=4, macaddr=fa:16:3e:07:00:fe,
}]},
}, powerstate=1, vmState=active, metadata={jenkins-boot-image-id=92bf9d42-a5ac-45f5-aa61-437d61661229, jenkins-cloud-name=openstack-rtp, jenkins-template-name=ops-vm-rtp-jnlp, jenkins-instance=https://jenkins.infra.myserver.com/, jenkins-scope=node:ops-vm-rtp-jnlp-1011:1392152704, jenkins-boot-source=Image jenkins-slave-master}}`

**Comment by olivergondza** [comment] 2020-04-07 19:07
Thanks, @rfateam2, it is confirmed. The [metadata update](https://github.com/jenkinsci/openstack-cloud-plugin/blob/40a9c66c7e2eba6f66ecbb8e5fbd8939bb6b17dd/plugin/src/main/java/jenkins/plugins/openstack/compute/JCloudsSlaveTemplate.java#L352) does not have the desired effect for some reason.

**Comment by rfateam2** [comment] 2020-04-07 21:31
@olivergondza Sure. Please, help with the direct link to download 2.51 version for a fresh install. Cannot downgrade version on a new system. Thank you.

**Comment by rfateam2** [comment] 2020-04-07 21:41
Sorry, I've found it in https://updates.jenkins-ci.org/download/plugins/openstack-cloud/

**Comment by kislinsk** [comment] 2020-07-01 10:16
Sorry, to bring this up again. Maybe I do not understand how this is not a critical issue, but as far as I can see this issue basically cripples the plugin for any professional use/environment for months now. If it this extremely hard to fix, wouldn't it be appropriate to roll back to the Compute Networking API until it is solved?

**Comment by toomer** [comment] 2020-08-27 11:44
We hit this problem as well again after upgrading to Jenkins 2.235.5 and OpenStack Cloud plugin 2.55
We had to downgrade the plugin to 2.51 version in order to spin up the OpenStack slaves. Now in effect, we are stuck with version 2.51 until this issue is solved.

**Comment by crcibordeaux** [comment] 2020-09-07 12:57
Same problem for me, I had to downgrade to resolve the problem

**Comment by olivergondza** [comment] 2020-09-09 08:25
Folks, I do not have an environment where I can replicate and verify a fix for this. If someone would like to pick this up, verify we are correct with our diagnosis (amended server does not have the IP address associated right away[1]) and contribute the fix, I would be happy to review it.

[1] https://github.com/jenkinsci/openstack-cloud-plugin/blob/40a9c66c7e2eba6f66ecbb8e5fbd8939bb6b17dd/plugin/src/main/java/jenkins/plugins/openstack/compute/JCloudsSlaveTemplate.java#L352

**Comment by toomer** [comment] 2021-04-16 13:23
Hi @olivergondza 
We would like to help with this bug.  We can't afford to stay at version 2.51 much longer. 
I'm going to start with creating the Jenkins test environment and replicate an issue.

**Comment by sunilkps** [comment] 2021-04-26 06:48
Hi @olivergondza ,

As you closed the jira as duplicate, Can we know when is the fix planned to be released?

**Comment by kislinsk** [comment] 2021-04-26 07:16
We are still interested in a fix, too. Kudos to @toomer for providing a test environment. Please do not let this serious issue die, @olivergondza.

**Comment by toomer** [comment] 2021-04-27 10:33
I manage to replicate the problem and from what see in the code there are some extra logging information which I hope will let us get to the bottom of that problem. 
From what I see so far there is some timing problem related to when the floating IP is added to the OpenStack slave VM. Here is a log file from jenkins.plugins.openstack. which indicate that: [jenkins-plugins-openstack.log](https://github.com/jenkinsci/openstack-cloud-plugin/files/6383800/jenkins-plugins-openstack.log)
It looks like after a couple of secs the plugin tries to use the correct floating (public) IP: 37.123.456.789

On the Jenkins when the slave is added it's still using the private IP: 10.3.0.13
Please take a look: [jenkins-slave-statup.log](https://github.com/jenkinsci/openstack-cloud-plugin/files/6383825/jenkins-slave-statup.log)

**Comment by olivergondza** [comment] 2021-04-28 10:31
@toomer, awesome. Thanks or confirmation!

The best course of fixing this seems to be to alter the [server refresh](https://github.com/jenkinsci/openstack-cloud-plugin/blob/38315dc3213d0f3a572d8dc7c2d594b088b49bdf/plugin/src/main/java/jenkins/plugins/openstack/compute/JCloudsSlaveTemplate.java#L355) into a retry loop until the IP changes or until ` Openstack#getAccessIpAddress` starts returning public address.

**Comment by sunilkps** [comment] 2021-04-30 06:45
@olivergondza  Is it getting fixed as per above-mentioned proposal?

**Comment by sunilkps** [comment] 2021-05-10 09:53
@olivergondza  Any further update on the fix?

**Comment by olivergondza** [comment] 2021-05-12 19:30
I have crafted a speculative fix for this here: https://github.com/jenkinsci/openstack-cloud-plugin/pull/319

Please verify that it resolves the situation on affected deployment, so we can integrate it.

Thanks!

**Comment by sunilkps** [comment] 2021-05-15 11:19
@olivergondza I have tested the fix and floating ip is getting assigned. Could you please integrate the fix?

Thanks

**Comment by olivergondza** [comment] 2021-05-19 19:26
@sunilkps, thanks for testing!

**Closed** 2021-05-19 19:26 UTC
Labels: help wanted

**Comment by olivergondza** [comment] 2021-05-19 19:31
Released as 2.58

**Comment by ssibahi** [comment] 2021-11-11 11:45
Hi,
I`m still experiencing the issue where plugin is not waiting for the floating ip and instead using the private ip.
Using version 2.60

**Comment by olivergondza** [comment] 2021-11-12 18:45
@ssibahi, please file separately attaching the details requested here, so we can have a look.
